spring.application.name=BookMyShow

spring.datasource.url=jdbc:mysql://localhost:3306/bms?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Jaydip123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
